#!/usr/bin/python
# -*- coding: utf-8 -*-

from moving.models import Chambre,Meuble

def do_it():
    Entree = Chambre.objects.get(id=10)
    meuble=Meuble(chambre=Entree,nom=u"banc",nom_pluriel=u"bancs",volume=0.34)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"armoire",nom_pluriel=u"armoires",volume=1.8)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"banc",nom_pluriel=u"bancs",volume=0.34)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"buffet",nom_pluriel=u"buffets",volume=1.15)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"chaise",nom_pluriel=u"chaises",volume=0.26)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"étagère",nom_pluriel=u"étagères",volume=0.60)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"fauteuil",nom_pluriel=u"fauteuils",volume=0.50)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"lampadaire",nom_pluriel=u"lampadaires",volume=0.27)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"lustre",nom_pluriel=u"lustres",volume=0.05)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"meuble à chaussures",nom_pluriel=u"meubles à chaussures",volume=0.45)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"meuble téléphone",nom_pluriel=u"meubles téléphones",volume=0.35)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"plante en pot",nom_pluriel=u"plantes en pot",volume=1.05)
    meuble.save()
    meuble=Meuble(chambre=Entree,nom=u"tableau",nom_pluriel=u"tableaux",volume=0.25)
    meuble.save()
    '''
    !	couloir = 
    Couloir	banc	bancs	0.34
    Couloir	buffet	buffets	1.60
    Couloir	chaise	chaises	0.26
    Couloir	étagères	0.50
    Couloir	lampadaire	0.27
    Couloir	lustre	0.05
    Couloir	plante	1.05
    Couloir	tableau	0.25
    '''
    Cuisine = Chambre.objects.get(id=3)
    '''
    !Cuisine	armoire	1.8
    !Cuisine	banc	0.34
    !Cuisine	buffet	1.15
    !Cuisine	chaise	0.26
    '''
    meuble=Meuble(chambre=Cuisine,nom=u"congélateur",nom_pluriel=u"congélateurs",volume=1.2)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"four",nom_pluriel=u"fours",volume=0.4)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"hotte",nom_pluriel=u"hottes",volume=0.2)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"lave vaisselle",nom_pluriel=u"lave vaisselle",volume=0.46)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"micro-onde",nom_pluriel=u"micro-ondes",volume=0.08)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"plaque de cuisson",nom_pluriel=u"plaques de cuisson",volume=0.05)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"piano de cuisson",nom_pluriel=u"pianos de cuisson",volume=0.6)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"plan de travail",nom_pluriel=u"plans de travail",volume=0.02)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"réfrigérateur",nom_pluriel=u"réfrigérateurs",volume=0.7)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"réfrigérateur (top)",nom_pluriel=u"réfrigérateurs (top)",volume=0.5)
    meuble.save()
    meuble=Meuble(chambre=Cuisine,nom=u"réfrigérateur américain",nom_pluriel=u"réfrigérateurs américains",volume=1.2)
    meuble.save()
    
    Salon = Chambre.objects.get(id=1)
    meuble=Meuble(chambre=Salon,nom=u"aquarium",nom_pluriel=u"aquariums",volume=0.60)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"bibliothèque",nom_pluriel=u"bibliothèques",volume=2.0)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"buffet",nom_pluriel=u"buffets",volume=1.85)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"bureau",nom_pluriel=u"bureaux",volume=1.80)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"canapé 2 places",nom_pluriel=u"canapés 2 places",volume=1.35)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"canapé 3 places",nom_pluriel=u"canapés 3 places",volume=1.85)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"canapé d'angle",nom_pluriel=u"canapés d'angle",volume=3.30)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"chaise",nom_pluriel=u"chaises",volume=0.26)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"enceinte hifi",nom_pluriel=u"enceintes hifis",volume=0.06)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"étagères",nom_pluriel=u"étagères",volume=0.60)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"fauteuil",nom_pluriel=u"fauteuils",volume=0.50)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"home cinéma",nom_pluriel=u"home cinémas",volume=0.60)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"lampadaire",nom_pluriel=u"lampadaires",volume=0.27)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"lustre",nom_pluriel=u"lustres",volume=0.05)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"lecteur VHS/DVD/Console",nom_pluriel=u"lecteurs VHS/DVD/Console",volume=0.02)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"meuble d'angle",nom_pluriel=u"meubles d'angle",volume=1.20)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"TV",nom_pluriel=u"TVs",volume=0.55)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"ordinateur",nom_pluriel=u"ordinateurs",volume=0.25)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"plante en pot",nom_pluriel=u"plantes en pot",volume=1.05)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"piano à queue",nom_pluriel=u"pianos à queue",volume=4.60)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"piano droit",nom_pluriel=u"pianos droits",volume=1.20)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"table à manger",nom_pluriel=u"table à manger",volume=1)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"table basse",nom_pluriel=u"tables basses",volume=0.25)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"table billards",nom_pluriel=u"table billards",volume=3.20)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"tableau",nom_pluriel=u"tableaux",volume=0.25)
    meuble.save()
    meuble=Meuble(chambre=Salon,nom=u"table à manger",nom_pluriel=u"table à manger",volume=1)
    meuble.save()
    
    Chambre1 = Chambre.objects.get(id=4)
    meuble=Meuble(chambre=Chambre1,nom=u"armoire 2 portes",nom_pluriel=u"armoires 2 portes",volume=1.2)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"armoire 3 portes",nom_pluriel=u"armoires 3 portes",volume=1.8)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"bureau",nom_pluriel=u"bureaux",volume=1.80)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"chaise",nom_pluriel=u"chaises",volume=0.26)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"chevet",nom_pluriel=u"chevets",volume=0.11)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"coiffeuse",nom_pluriel=u"coiffeuses",volume=1.25)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"commode",nom_pluriel=u"commodes",volume=0.65)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"lampadaire",nom_pluriel=u"lampadaires",volume=0.27)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"lit",nom_pluriel=u"lits",volume=0.80)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"lit 2 places",nom_pluriel=u"lits 2 places",volume=1.7)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"lit canapé",nom_pluriel=u"lit canapé",volume=1.35)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"tableau",nom_pluriel=u"tableaux",volume=0.25)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"tapis",nom_pluriel=u"tapis",volume=0.35)
    meuble.save()
    meuble=Meuble(chambre=Chambre1,nom=u"lit bébé",nom_pluriel=u"lits bébé",volume=0.65)
    meuble.save()
    
    Salbain = Chambre.objects.get(id=5)
    meuble=Meuble(chambre=Salbain,nom=u"bac à linge",nom_pluriel=u"bacs à linge",volume=0.15)
    meuble.save()
    meuble=Meuble(chambre=Salbain,nom=u"lave linge",nom_pluriel=u"lave linge",volume=0.63)
    meuble.save()
    meuble=Meuble(chambre=Salbain,nom=u"miroir",nom_pluriel=u"miroirs",volume=0.05)
    meuble.save()
    meuble=Meuble(chambre=Salbain,nom=u"sèche linge",nom_pluriel=u"sèche linge",volume=0.63)
    meuble.save()
    meuble=Meuble(chambre=Salbain,nom=u"table à langer",nom_pluriel=u"table à langer",volume=0.63)
    meuble.save()
    meuble=Meuble(chambre=Salbain,nom=u"tabouret",nom_pluriel=u"tabourets",volume=0.20)
    meuble.save()
    
    Debarras = Chambre.objects.get(id=6)
    meuble=Meuble(chambre=Debarras,nom=u"boite archive",nom_pluriel=u"boites archive",volume=0.02)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"climatiseur mobile",nom_pluriel=u"climatiseurs mobiles",volume=0.30)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"lampe halogène",nom_pluriel=u"lampes halogènes",volume=0.27)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"lit pliant",nom_pluriel=u"lits pliants",volume=0.42)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"livres en carton",nom_pluriel=u"livres en carton",volume=0.06)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"meuble de rangement",nom_pluriel=u"meubles de rangement",volume=0.50)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"garde-robe",nom_pluriel=u"garde-robe",volume=2)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"caisse à outils",nom_pluriel=u"caisse à outils",volume=0.05)
    meuble.save()
    meuble=Meuble(chambre=Debarras,nom=u"ventilateur",nom_pluriel=u"ventilateurs",volume=0.18)
    meuble.save()
    
    Cave = Chambre.objects.get(id=7)
    meuble=Meuble(chambre=Cave,nom=u"cantine",nom_pluriel=u"cantines",volume=0.30)
    meuble.save()
    meuble=Meuble(chambre=Cave,nom=u"carton",nom_pluriel=u"cartons",volume=0.06)
    meuble.save()
    meuble=Meuble(chambre=Cave,nom=u"cave à vin",nom_pluriel=u"cave à vin",volume=1.8)
    meuble.save()
    meuble=Meuble(chambre=Cave,nom=u"matériel sport",nom_pluriel=u"matériel sport",volume=0.90)
    meuble.save()
    
    Garage = Chambre.objects.get(id=8)
    meuble=Meuble(chambre=Garage,nom=u"bicyclette",nom_pluriel=u"bicyclettes",volume=0.6)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"congélateur",nom_pluriel=u"congélateurs",volume=1.2)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"jeu volumineux",nom_pluriel=u"jeux volumineux",volume=1)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"moto/scooter",nom_pluriel=u"motos/scooters",volume=1.65)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"planche à voile",nom_pluriel=u"planches à voile",volume=1.05)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"sac de golf",nom_pluriel=u"sacs de golf",volume=0.2)
    meuble.save()
    meuble=Meuble(chambre=Garage,nom=u"table de ping-pong",nom_pluriel=u"tables de ping-pong",volume=3.3)
    meuble.save()
    
    
    Jardin = Chambre.objects.get(id=9)
    meuble=Meuble(chambre=Jardin,nom=u"bac à fleur",nom_pluriel=u"bacs à fleurs",volume=0.4)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"barbecue",nom_pluriel=u"barbacue",volume=0.55)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"brouette",nom_pluriel=u"brouettes",volume=0.45)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"chaise longue",nom_pluriel=u"chaises longues",volume=0.55)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"chaise jardin",nom_pluriel=u"chaises jardin",volume=0.15)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"échelle jardin",nom_pluriel=u"échelles jardin",volume=0.15)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"piscine portable",nom_pluriel=u"piscines portables",volume=1)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"portique/jeu/balançoire",nom_pluriel=u"portique/jeu/balançoire",volume=0.35)
    meuble.save()
    meuble=Meuble(chambre=Jardin,nom=u"tondeuse",nom_pluriel=u"tondeuses",volume=0.2)
    meuble.save()